#ifndef _COUNT_TEMP_DECL_H_INCLUDED_
#define _COUNT_TEMP_DECL_H_INCLUDED_

#define NTEMP_ROUTINE(FUN_NAME) FUN_NAME##_ntemp()
#define NTEMP(FUN_NAME) NTEMP_ROUTINE(FUN_NAME)
#define NTEMP_DECL(FUN_NAME) size_t NTEMP(FUN_NAME)

#endif